name: Build

on:
  push:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2' 
      - name: Build with Gradle
        run: cd backend && ./gradlew bootJar
      - name: Run Junit test
        run: cd backend && ./gradlew clean build test || cat build/reports/tests/test/classes/com.example.webmath.controller.PythonControllerTest.html && cat build/reports/tests/test/packages/com.example.webmath.controller.html

  build-static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm
        run: sudo apt-get update && sudo apt-get install npm
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Build static
        run: cd frontend && npm run build
